-- --------------------------------------------------------
-- Servidor:                     69.6.248.181
-- Versão do servidor:           8.0.45-36 - Percona Server (GPL), Release 36, Revision 8fe4a72d
-- OS do Servidor:               Linux
-- HeidiSQL Versão:              12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Copiando dados para a tabela cleit467_siteirana.produtos: ~7 rows (aproximadamente)
INSERT IGNORE INTO `produtos` (`id`, `categoria_id`, `nome`, `slug`, `sku`, `descricao_curta`, `descricao_completa`, `composicao`, `modo_uso`, `cuidados`, `seo_titulo`, `seo_descricao`, `tags`, `preco_venda`, `margem_desejada`, `custo_calculado`, `lucro_calculado`, `margem_real`, `estoque_atual`, `estoque_minimo`, `ativo`, `criado_em`, `atualizado_em`) VALUES
	(1, 4, 'Talismã', 'talisma', NULL, 'Prosperidade, abertura de caminhos e energia de conquista em um incenso artesanal natural.', 'O Incenso Talismã da Iraná Natural foi desenvolvido para quem busca mais do que um aroma — busca movimento, energia e intenção.\r\n\r\nCom uma composição 100% natural e artesanal, ele traz uma fragrância envolvente, levemente especiada e adocicada, criando um ambiente acolhedor e energizante.\r\n\r\nMais do que perfumar, este incenso atua como um verdadeiro aliado energético:\r\n• Estimula prosperidade e entusiasmo\r\n• Favorece abertura de caminhos\r\n• Eleva a vibração do ambiente\r\n• Ideal para rituais, meditações ou uso diário\r\n\r\nCada vareta carrega a essência do propósito: prosperar é florir de dentro para fora.', 'Resina olíbano, mirra, sândalo em pó, alecrim, arruda.', 'Acenda cuidadosamente a ponta do incenso até formar uma pequena chama. Aguarde alguns segundos e apague a chama, permitindo que a brasa libere a fumaça aromática no ambiente. Utilize em suportes adequados e aproveite o momento para conexão, relaxamento, meditação ou uso ritualístico.', 'Mantenha fora do alcance de crianças e animais domésticos. Utilize em local arejado, longe de materiais inflamáveis e nunca deixe o incenso aceso sem supervisão. Após o uso, certifique-se de que a brasa esteja completamente apagada.', 'Incenso Talismã para Prosperidade e Abertura de Caminhos', 'Incenso natural para prosperidade e abertura de caminhos. Ideal para atrair abundância e ativar energia de conquista.', 'prosperidade,abertura de caminhos,energia de conquista,abundância,sucesso,ritual prosperidade', 19.00, 60.00, 2.1300, 16.87, 88.79, 20, 5, 1, '2026-05-06 02:26:17', '2026-05-06 23:19:52'),
	(2, 4, 'Sereno', 'sereno', NULL, 'Calma, relaxamento e bem-estar para desacelerar e criar um ambiente acolhedor.', 'O Incenso Sereno da Iraná Natural é um convite para desacelerar e voltar para si.\r\n\r\nCom fragrância floral suave e relaxante, promove calma e acolhimento.\r\n\r\nBenefícios:\r\n• Relaxamento\r\n• Tranquilidade\r\n• Bem-estar emocional\r\n• Descanso mental\r\n\r\nUm sopro manso que repousa a mente.', 'Lavanda, camomila, resina olíbano, rosa vermelha.', 'Acenda cuidadosamente a ponta do incenso até formar uma pequena chama. Aguarde alguns segundos e apague a chama, permitindo que a brasa libere a fumaça aromática no ambiente. Utilize em suportes adequados e aproveite o momento para conexão, relaxamento, meditação ou uso ritualístico.', 'Mantenha fora do alcance de crianças e animais domésticos. Utilize em local arejado, longe de materiais inflamáveis e nunca deixe o incenso aceso sem supervisão. Após o uso, certifique-se de que a brasa esteja completamente apagada.', 'Incenso Sereno para Relaxamento e Tranquilidade', 'Incenso natural para relaxamento, calma mental e bem-estar. Ideal para desacelerar e criar um ambiente acolhedor.', 'relaxamento,calma mental,tranquilidade,autocuidado,descanso mental', 19.00, 55.00, 1.8200, 17.18, 90.42, 15, 5, 1, '2026-05-06 02:26:17', '2026-05-06 23:35:45'),
	(3, 4, 'Rubro', 'rubro', NULL, 'Energia, vitalidade e autoestima para despertar presença e força interior.', 'O Incenso Rubro da Iraná Natural desperta força, presença e vitalidade.\r\n\r\nCom fragrância floral intensa, quente e adocicada, ativa confiança e autoestima.\r\n\r\nBenefícios:\r\n• Energia e disposição\r\n• Autoestima e autoconfiança\r\n• Vitalidade\r\n• Presença pessoal\r\n\r\nAcender o fogo interno e reconhecer a beleza de existir em si.', 'Rosa vermelha, mirra, sândalo em pó, lavanda.', 'Acenda cuidadosamente a ponta do incenso até formar uma pequena chama. Aguarde alguns segundos e apague a chama, permitindo que a brasa libere a fumaça aromática no ambiente. Utilize em suportes adequados e aproveite o momento para conexão, relaxamento, meditação ou uso ritualístico.', 'Mantenha fora do alcance de crianças e animais domésticos. Utilize em local arejado, longe de materiais inflamáveis e nunca deixe o incenso aceso sem supervisão. Após o uso, certifique-se de que a brasa esteja completamente apagada.', 'Incenso Rubro para Energia, Autoestima e Vitalidade', 'Incenso natural para aumentar energia, autoestima e confiança. Ideal para ativar presença e força pessoal.', 'energia vital,autoestima,confiança,motivação,vitalidade,magnetismo', 19.00, 60.00, 2.3100, 16.69, 87.84, 10, 5, 1, '2026-05-06 02:26:17', '2026-05-06 23:32:48'),
	(4, 4, 'Aruanda', 'aruanda', NULL, 'Proteção espiritual e limpeza energética para ambientes, rituais e conexão com o sagrado.', 'O Incenso Aruanda da Iraná Natural é um chamado à conexão com o sagrado, à limpeza do que pesa e à proteção do que importa.\r\n\r\nCom fragrância herbal e amadeirada, cria um campo de presença e espiritualidade.\r\n\r\nBenefícios:\r\n• Limpeza energética\r\n• Proteção espiritual\r\n• Conexão com o sagrado\r\n• Ideal para rituais e orações\r\n\r\nFumaça que reza, vento que leva, fé que permanece.', 'Arruda, sândalo, cravo e ervas naturais.', 'Acenda cuidadosamente a ponta do incenso até formar uma pequena chama. Aguarde alguns segundos e apague a chama, permitindo que a brasa libere a fumaça aromática no ambiente. Utilize em suportes adequados e aproveite o momento para conexão, relaxamento, meditação ou uso ritualístico.', 'Mantenha fora do alcance de crianças e animais domésticos. Utilize em local arejado, longe de materiais inflamáveis e nunca deixe o incenso aceso sem supervisão. Após o uso, certifique-se de que a brasa esteja completamente apagada.', '', '', '', 19.00, 50.00, 2.0500, 16.95, 89.21, 25, 5, 1, '2026-05-06 02:26:17', '2026-05-07 00:04:27'),
	(5, 2, 'Desatar', 'desatar', NULL, 'Blend de ervas medicinais para soltar bloqueios, aliviar tensões e facilitar novos começos.', 'O Chá Desatar foi elaborado para quem sente o peso de situações travadas, de emoções represadas ou de ciclos que não se fecham. Sua fórmula une ervas com propriedades digestivas, calmantes e energeticamente libertadoras, criando um ritual de chá que cuida do corpo e da alma.', 'Abacaxi, Erva doce, Manjericão, Pitanga, essência de abacaxi e Hortelã.', 'Infuse 1 colher de chá em 200ml de água quente (não fervente, ~80°C) por 5 minutos. Beba com presença e intenção.', 'Produto natural, sem conservantes. Consulte um profissional de saúde em caso de gravidez ou uso de medicamentos. Conserve em local seco.', '', '', '', 19.00, 65.00, 3.0000, 16.00, 84.21, 12, 3, 0, '2026-05-06 02:26:17', '2026-05-06 23:37:31'),
	(6, 4, 'Candeia', 'candeia', NULL, 'Clareza, leveza e renovação energética para transformar o ambiente e o dia a dia.', 'O Incenso Candeia da Iraná Natural é um convite para acender a luz que já existe dentro de você.\r\n\r\nCom fragrância floral suave e levemente adocicada, promove bem-estar, clareza e leveza.\r\n\r\nBenefícios:\r\n• Clareza mental\r\n• Renovação energética\r\n• Alegria e leveza\r\n• Equilíbrio do ambiente\r\n\r\nLuz que nasce de dentro, chama que guia o caminho.', '', 'Acenda cuidadosamente a ponta do incenso até formar uma pequena chama. Aguarde alguns segundos e apague a chama, permitindo que a brasa libere a fumaça aromática no ambiente. Utilize em suportes adequados e aproveite o momento para conexão, relaxamento, meditação ou uso ritualístico.', 'Mantenha fora do alcance de crianças e animais domésticos. Utilize em local arejado, longe de materiais inflamáveis e nunca deixe o incenso aceso sem supervisão. Após o uso, certifique-se de que a brasa esteja completamente apagada.', 'Incenso Candeia para Luz, Clareza e Renovação Energética', 'Incenso natural para clareza mental, leveza e renovação energética. Aroma suave para equilíbrio e bem-estar diário.', 'clareza mental,luz interior,renovação energética,energia positiva,bem-estar', 19.00, 50.00, 0.0000, 19.00, 100.00, 0, 5, 1, '2026-05-06 23:25:19', '2026-05-06 23:25:19'),
	(7, 4, 'Púrpura', 'purpura', NULL, 'Introspecção, clareza interior e equilíbrio emocional para momentos de reconexão.', 'O Incenso Púrpura da Iraná Natural é um convite ao silêncio que transforma.\r\n\r\nCom fragrância floral profunda e levemente terrosa, cria um ambiente ideal para reflexão e reconexão.\r\n\r\nBenefícios:\r\n• Introspecção\r\n• Clareza mental\r\n• Equilíbrio emocional\r\n• Autoconhecimento\r\n\r\nO silêncio que ensina, a sabedoria que acolhe.', '', 'Acenda cuidadosamente a ponta do incenso até formar uma pequena chama. Aguarde alguns segundos e apague a chama, permitindo que a brasa libere a fumaça aromática no ambiente. Utilize em suportes adequados e aproveite o momento para conexão, relaxamento, meditação ou uso ritualístico.', 'Mantenha fora do alcance de crianças e animais domésticos. Utilize em local arejado, longe de materiais inflamáveis e nunca deixe o incenso aceso sem supervisão. Após o uso, certifique-se de que a brasa esteja completamente apagada.', 'Incenso Púrpura para Introspecção e Clareza Interior', 'Incenso natural para introspecção, autoconhecimento e clareza mental. Ideal para meditação e tomada de decisão.', 'introspecção,autoconhecimento,clareza emocional,meditação,sabedoria interior', 19.00, 50.00, 0.0000, 19.00, 100.00, 0, 5, 1, '2026-05-06 23:28:53', '2026-05-06 23:28:53');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
